<input class="search form-control" placeholder="Search" width="100px"/><br />
<?php

if(isset($this->searchAndFilter)) {
	echo $this->searchAndFilter;
}

?>
<hr>
<table class="table">
	<?php

	if(isset($this->colorLine)) {
		$colorLine[0] = $this->colorLine[0];
	} else {
		$colorLine[0] = null;
	}

	$values = $this->values;
	echo '<thead>';
	if($values !== null && !empty($values)) {
		if(isset($this->showAttributes)) {
			foreach($this->showAttributes as $name => $attrConfig) {
				if(isset($attrConfig['hide']) && $attrConfig['hide']) {
					echo '<th style="display: none">' . $name . '</th>';
				} elseif(isset($attrConfig['name'])) {
					echo '<th class="attribute highlight_list_item" data-attribute-name="' . $name . '" >' . $attrConfig['name']. '</th>';
				} else {
					echo '<th class="attribute highlight_list_item" data-attribute-name="' . $name . '" >' . $name . '</th>';
				}
			}
		}
	}
	if(isset($this->actions) && $this->actions) {
		echo '<th class="highlight_list_item">Aktionen</th>';
	}
	echo '</thead>';
	echo '<tbody class="list">';
	foreach($values as $single) {
		/**
		 * @var \Reinoldus\Doctrine\Entity\BaseEntity $single
		 */
		if($colorLine[0] !== null && is_callable($colorLine[0]) && $single !== null) {
			echo "<tr ";
			echo $colorLine[0]($single);
			echo ">";
		} else {
			echo "<tr>";
		}
		$handleAttribute = function($attribute, $hiddenAttributes, $single, $alternativeFunctions) {
			if(!in_array($attribute, $this->ignoreAttribute)) {
				if(in_array($attribute, $hiddenAttributes)) {
					echo '<td class="' . $attribute . '" style="display:none;">';
				} else {
					echo '<td class="' . $attribute . '">';
				}

				$var = $single->{"get" . $attribute}();
				if($var !== null) {
					if(array_key_exists($attribute, $alternativeFunctions)) {
						if(is_callable($alternativeFunctions[$attribute])) {
							echo $alternativeFunctions[$attribute]($var);
						} else {
							echo $var->{$alternativeFunctions[$attribute]}();
						}
					} elseif(is_a($var, 'DateTime')) {
						echo $var->format('Y-m-d H:i:s');
					} else {
						echo $var;
					}
				}
				echo '</td>';
			}
		};

		foreach($this->showAttributes as $name => $attrConfig) {
			if(isset($attrConfig['hide']) && $attrConfig['hide']) {
				echo '<td class="' . $name . '" style="display:none;">';
			} else {
				echo '<td class="' . $name . '" >';
			}

			$var = $single->{"get" . $name}();
			if($var !== null) {
				if(isset($attrConfig['func'])) {
					if(is_callable($attrConfig['func'])) {
						echo $attrConfig['func']($single);
					} else {
						echo $var->{$attrConfig['func']}();
					}
				} elseif(is_a($var, 'DateTime')) {
					echo $var->format('Y-m-d H:i:s');
				} else {
					echo $var;
				}
			}
			echo '</td>';
		}

		if(isset($this->actions) && $this->actions) {
			echo '<td>';
			?>
			<a class="listjs_edit" data-id="<?=$single->getId()?>"><span class="glyphicon glyphicon-pencil"></span></a>
			<a class="listjs_delete" data-id="<?=$single->getId()?>"><span class="glyphicon glyphicon-remove"></span></a>
			<?php
			echo '</td>';
		}
		echo '</tr>';
	}
	echo '</tbody>';
	?>
</table>
<ul class="pagination"></ul>